name: conda
description: Run commands in conda environments.
author: Jens Preussner<jens.preussner@mpi-bn.mpg.de>
requirements:
  - conda
configuration:
  properties:
    packages:
      type: string
    environment:
      type: string
    update:
      type: boolean
